In [1]:
from datascience import *
path_data = '../../data/data8/'
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')

cones = Table.read_table(path_data + "cones.csv")
nba = Table.read_table(path_data + "nba_salaries.csv")
movies = Table.read_table(path_data + "movies_by_year.csv")

In [2]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [3]:
cones.select("Flavor")

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [4]:
cones.select("Flavor", "Price")

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [5]:
no_colours = cones.drop("Color")

In [6]:
no_colours

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

In [7]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [8]:
cones.where("Flavor", "chocolate") # label, value

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

## Salaries in the NBA

In [9]:
nba

PLAYER           | POSITION | TEAM          | '15-'16 SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [10]:
nba.where("PLAYER", "Stephen Curry")

PLAYER        | POSITION | TEAM                  | '15-'16 SALARY
Stephen Curry | PG       | Golden State Warriors | 11.3708

In [16]:
nba = nba.relabeled("'15-'16 SALARY", "SALARY")

In [17]:
nba

PLAYER           | POSITION | TEAM          | SALARY
Paul Millsap     | PF       | Atlanta Hawks | 18.6717
Al Horford       | C        | Atlanta Hawks | 12
Tiago Splitter   | C        | Atlanta Hawks | 9.75625
Jeff Teague      | PG       | Atlanta Hawks | 8
Kyle Korver      | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha  | SF       | Atlanta Hawks | 4
Mike Scott       | PF       | Atlanta Hawks | 3.33333
Kent Bazemore    | SF       | Atlanta Hawks | 2
Dennis Schroder  | PG       | Atlanta Hawks | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks | 1.30452
... (407 rows omitted)

In [18]:
minard = Table.read_table(path_data + "minard.csv")

In [19]:
minard

Longitude | Latitude | City        | Direction | Survivors
32        | 54.8     | Smolensk    | Advance   | 145000
33.2      | 54.9     | Dorogobouge | Advance   | 140000
34.4      | 55.5     | Chjat       | Advance   | 127100
37.6      | 55.8     | Moscou      | Advance   | 100000
34.3      | 55.2     | Wixma       | Retreat   | 55000
32        | 54.6     | Smolensk    | Retreat   | 24000
30.4      | 54.4     | Orscha      | Retreat   | 20000
26.8      | 54.3     | Moiodexno   | Retreat   | 12000

In [20]:
minard.labels

('Longitude', 'Latitude', 'City', 'Direction', 'Survivors')

In [21]:
minard.column("Survivors")

array([145000, 140000, 127100, 100000,  55000,  24000,  20000,  12000])

In [22]:
initial = minard.column("Survivors").item(0)

minard = minard.with_columns("Percent Surviving",
                             minard.column("Survivors")/initial)
minard

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 1
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 0.965517
34.4      | 55.5     | Chjat       | Advance   | 127100    | 0.876552
37.6      | 55.8     | Moscou      | Advance   | 100000    | 0.689655
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 0.37931
32        | 54.6     | Smolensk    | Retreat   | 24000     | 0.165517
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 0.137931
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 0.0827586

In [23]:
minard.set_format("Percent Surviving", PercentFormatter)

Longitude | Latitude | City        | Direction | Survivors | Percent Surviving
32        | 54.8     | Smolensk    | Advance   | 145000    | 100.00%
33.2      | 54.9     | Dorogobouge | Advance   | 140000    | 96.55%
34.4      | 55.5     | Chjat       | Advance   | 127100    | 87.66%
37.6      | 55.8     | Moscou      | Advance   | 100000    | 68.97%
34.3      | 55.2     | Wixma       | Retreat   | 55000     | 37.93%
32        | 54.6     | Smolensk    | Retreat   | 24000     | 16.55%
30.4      | 54.4     | Orscha      | Retreat   | 20000     | 13.79%
26.8      | 54.3     | Moiodexno   | Retreat   | 12000     | 8.28%

Useful functions for the table are:
- select, drop, column

In [25]:
nba.show(20)

In [26]:
# sort by player names
nba.sort("PLAYER").show(10)

In [27]:
nba.sort("SALARY")

PLAYER                 | POSITION | TEAM                 | SALARY
Thanasis Antetokounmpo | SF       | New York Knicks      | 0.030888
Jordan McRae           | SG       | Phoenix Suns         | 0.049709
Cory Jefferson         | PF       | Phoenix Suns         | 0.049709
Elliot Williams        | SG       | Memphis Grizzlies    | 0.055722
Orlando Johnson        | SG       | Phoenix Suns         | 0.055722
Phil Pressey           | PG       | Phoenix Suns         | 0.055722
Keith Appling          | PG       | Orlando Magic        | 0.061776
Sean Kilpatrick        | SG       | Denver Nuggets       | 0.099418
Erick Green            | PG       | Utah Jazz            | 0.099418
Jeff Ayres             | PF       | Los Angeles Clippers | 0.111444
... (407 rows omitted)

In [29]:
nba.sort("SALARY", descending=True)

PLAYER          | POSITION | TEAM                  | SALARY
Kobe Bryant     | SF       | Los Angeles Lakers    | 25
Joe Johnson     | SF       | Brooklyn Nets         | 24.8949
LeBron James    | SF       | Cleveland Cavaliers   | 22.9705
Carmelo Anthony | SF       | New York Knicks       | 22.875
Dwight Howard   | C        | Houston Rockets       | 22.3594
Chris Bosh      | PF       | Miami Heat            | 22.1927
Chris Paul      | PG       | Los Angeles Clippers  | 21.4687
Kevin Durant    | SF       | Oklahoma City Thunder | 20.1586
Derrick Rose    | PG       | Chicago Bulls         | 20.0931
Dwyane Wade     | SG       | Miami Heat            | 20
... (407 rows omitted)

In [30]:
help(nba.sort)

Help on method sort in module datascience.tables:

sort(column_or_label, descending=False, distinct=False) method of datascience.tables.Table instance
    Return a Table of rows sorted according to the values in a column.

    Args:
        ``column_or_label``: the column whose values are used for sorting.

        ``descending``: if True, sorting will be in descending, rather than
            ascending order.

        ``distinct``: if True, repeated values in ``column_or_label`` will
            be omitted.

    Returns:
        An instance of ``Table`` containing rows sorted based on the values
        in ``column_or_label``.

    >>> marbles = Table().with_columns(
    ...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
    ...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
    ...    "Amount", make_array(4, 6, 12, 7, 9, 2),
    ...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00))
    >>> marbles
    Color | Shape       | Amount | Price
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 6      | 1.3
    Blue  | Rectangular | 12     | 2
    Red   | Round       | 7      | 1.75
    Green | Rectangular | 9      | 1.4
    Green | Round       | 2      | 1
    >>> marbles.sort("Amount")
    Color | Shape       | Amount | Price
    Green | Round       | 2      | 1
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 6      | 1.3
    Red   | Round       | 7      | 1.75
    Green | Rectangular | 9      | 1.4
    Blue  | Rectangular | 12     | 2
    >>> marbles.sort("Amount", descending = True)
    Color | Shape       | Amount | Price
    Blue  | Rectangular | 12     | 2
    Green | Rectangular | 9      | 1.4
    Red   | Round       | 7      | 1.75
    Green | Rectangular | 6      | 1.3
    Red   | Round       | 4      | 1.3
    Green | Round       | 2      | 1
    >>> marbles.sort(3) # the Price column
    Color | Shape       | Amount | Price
    Green | Round       | 2      | 1
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 6      | 1.3
    Green | Rectangular | 9      | 1.4
    Red   | Round       | 7      | 1.75
    Blue  | Rectangular | 12     | 2
    >>> marbles.sort(3, distinct = True)
    Color | Shape       | Amount | Price
    Green | Round       | 2      | 1
    Red   | Round       | 4      | 1.3
    Green | Rectangular | 9      | 1.4
    Red   | Round       | 7      | 1.75
    Blue  | Rectangular | 12     | 2

In [31]:
nba.sort?

Signature: nba.sort(column_or_label, descending=False, distinct=False)
Docstring:
Return a Table of rows sorted according to the values in a column.

Args:
    ``column_or_label``: the column whose values are used for sorting.

    ``descending``: if True, sorting will be in descending, rather than
        ascending order.

    ``distinct``: if True, repeated values in ``column_or_label`` will
        be omitted.

Returns:
    An instance of ``Table`` containing rows sorted based on the values
    in ``column_or_label``.

>>> marbles = Table().with_columns(
...    "Color", make_array("Red", "Green", "Blue", "Red", "Green", "Green"),
...    "Shape", make_array("Round", "Rectangular", "Rectangular", "Round", "Rectangular", "Round"),
...    "Amount", make_array(4, 6, 12, 7, 9, 2),
...    "Price", make_array(1.30, 1.30, 2.00, 1.75, 1.40, 1.00))
>>> marbles
Color | Shape       | Amount | Price
Red   | Round       | 4      | 1.3
Green | Rectangular | 6      | 1.3
Blue  | Rectangular | 12     | 2
Red   | Round       | 7      | 1.75
Green | Rectangular | 9      | 1.4
Green | Round       | 2      | 1
>>> marbles.sort("Amount")
Color | Shape       | Amount | Price
Green | Round       | 2      | 1
Red   | Round       | 4      | 1.3
Green | Rectangular | 6      | 1.3
Red   | Round       | 7      | 1.75
Green | Rectangular | 9      | 1.4
Blue  | Rectangular | 12     | 2
>>> marbles.sort("Amount", descending = True)
Color | Shape       | Amount | Price
Blue  | Rectangular | 12     | 2
Green | Rectangular | 9      | 1.4
Red   | Round       | 7      | 1.75
Green | Rectangular | 6      | 1.3
Red   | Round       | 4      | 1.3
Green | Round       | 2      | 1
>>> marbles.sort(3) # the Price column
Color | Shape       | Amount | Price
Green | Round       | 2      | 1
Red   | Round       | 4      | 1.3
Green | Rectangular | 6      | 1.3
Green | Rectangular | 9      | 1.4
Red   | Round       | 7      | 1.75
Blue  | Rectangular | 12     | 2
>>> marbles.sort(3, distinct = True)
Color | Shape       | Amount | Price
Green | Round       | 2      | 1
Red   | Round       | 4      | 1.3
Green | Rectangular | 9      | 1.4
Red   | Round       | 7      | 1.75
Blue  | Rectangular | 12     | 2
File:      ~/Projects/Python/learning/.venv/lib/python3.12/site-packages/datascience/tables.py
Type:      method

## row selection : uses take

In [32]:
nba.take(1)

PLAYER     | POSITION | TEAM          | SALARY
Al Horford | C        | Atlanta Hawks | 12

In [33]:
nba.take(np.arange(3,8))

PLAYER          | POSITION | TEAM          | SALARY
Jeff Teague     | PG       | Atlanta Hawks | 8
Kyle Korver     | SG       | Atlanta Hawks | 5.74648
Thabo Sefolosha | SF       | Atlanta Hawks | 4
Mike Scott      | PF       | Atlanta Hawks | 3.33333
Kent Bazemore   | SF       | Atlanta Hawks | 2

## Rows again with `where`

In [34]:
nba.where("SALARY", are.above(10))

PLAYER         | POSITION | TEAM              | SALARY
Paul Millsap   | PF       | Atlanta Hawks     | 18.6717
Al Horford     | C        | Atlanta Hawks     | 12
Joe Johnson    | SF       | Brooklyn Nets     | 24.8949
Thaddeus Young | PF       | Brooklyn Nets     | 11.236
Al Jefferson   | C        | Charlotte Hornets | 13.5
Nicolas Batum  | SG       | Charlotte Hornets | 13.1253
Kemba Walker   | PG       | Charlotte Hornets | 12
Derrick Rose   | PG       | Chicago Bulls     | 20.0931
Jimmy Butler   | SG       | Chicago Bulls     | 16.4075
Joakim Noah    | C        | Chicago Bulls     | 13.4
... (59 rows omitted)

In [35]:
nba.where("SALARY", are.above(10)).sort("SALARY")

PLAYER          | POSITION | TEAM                 | SALARY
DeMar DeRozan   | SG       | Toronto Raptors      | 10.05
Gerald Wallace  | SF       | Philadelphia 76ers   | 10.1059
Luol Deng       | SF       | Miami Heat           | 10.1516
Monta Ellis     | SG       | Indiana Pacers       | 10.3
Wilson Chandler | SF       | Denver Nuggets       | 10.4494
Brendan Haywood | C        | Cleveland Cavaliers  | 10.5225
Jrue Holiday    | PG       | New Orleans Pelicans | 10.5955
Tyreke Evans    | SG       | New Orleans Pelicans | 10.7346
Marcin Gortat   | C        | Washington Wizards   | 11.2174
Thaddeus Young  | PF       | Brooklyn Nets        | 11.236
... (59 rows omitted)

In [36]:
nba.where("PLAYER", are.equal_to("Stephen Curry"))

PLAYER        | POSITION | TEAM                  | SALARY
Stephen Curry | PG       | Golden State Warriors | 11.3708

In [37]:
nba.where('TEAM', are.equal_to('Golden State Warriors')).show()

In [38]:
nba.where("TEAM", "Denver Nuggets")

PLAYER            | POSITION | TEAM           | SALARY
Danilo Gallinari  | SF       | Denver Nuggets | 14
Kenneth Faried    | PF       | Denver Nuggets | 11.236
Wilson Chandler   | SF       | Denver Nuggets | 10.4494
JJ Hickson        | C        | Denver Nuggets | 5.6135
Jameer Nelson     | PG       | Denver Nuggets | 4.345
Will Barton       | SF       | Denver Nuggets | 3.53333
Emmanuel Mudiay   | PG       | Denver Nuggets | 3.10224
Darrell Arthur    | PF       | Denver Nuggets | 2.814
Jusuf Nurkic      | C        | Denver Nuggets | 1.842
Joffrey Lauvergne | C        | Denver Nuggets | 1.70972
... (4 rows omitted)

### Multiple Features and `where`

In [39]:
nba.where("POSITION", "PG").where("SALARY", are.above(15))

PLAYER            | POSITION | TEAM                  | SALARY
Derrick Rose      | PG       | Chicago Bulls         | 20.0931
Kyrie Irving      | PG       | Cleveland Cavaliers   | 16.4075
Chris Paul        | PG       | Los Angeles Clippers  | 21.4687
Russell Westbrook | PG       | Oklahoma City Thunder | 16.7442
John Wall         | PG       | Washington Wizards    | 15.852

In [40]:
nba.where("SALARY", are.between(10, 10.5))

PLAYER          | POSITION | TEAM               | SALARY
Wilson Chandler | SF       | Denver Nuggets     | 10.4494
Monta Ellis     | SG       | Indiana Pacers     | 10.3
Luol Deng       | SF       | Miami Heat         | 10.1516
Gerald Wallace  | SF       | Philadelphia 76ers | 10.1059
Danny Green     | SG       | San Antonio Spurs  | 10
DeMar DeRozan   | SG       | Toronto Raptors    | 10.05

In [41]:
nba.where("TEAM", are.containing("Warriors"))

PLAYER            | POSITION | TEAM                  | SALARY
Klay Thompson     | SG       | Golden State Warriors | 15.501
Draymond Green    | PF       | Golden State Warriors | 14.2609
Andrew Bogut      | C        | Golden State Warriors | 13.8
Andre Iguodala    | SF       | Golden State Warriors | 11.7105
Stephen Curry     | PG       | Golden State Warriors | 11.3708
Jason Thompson    | PF       | Golden State Warriors | 7.00847
Shaun Livingston  | PG       | Golden State Warriors | 5.54373
Harrison Barnes   | SF       | Golden State Warriors | 3.8734
Marreese Speights | C        | Golden State Warriors | 3.815
Leandro Barbosa   | SG       | Golden State Warriors | 2.5
... (4 rows omitted)

In [42]:
# get both PG and SG (point guards and shooting guards)
nba.where("POSITION", are.containing("G"))

PLAYER           | POSITION | TEAM           | SALARY
Jeff Teague      | PG       | Atlanta Hawks  | 8
Kyle Korver      | SG       | Atlanta Hawks  | 5.74648
Dennis Schroder  | PG       | Atlanta Hawks  | 1.7634
Tim Hardaway Jr. | SG       | Atlanta Hawks  | 1.30452
Jason Richardson | SG       | Atlanta Hawks  | 0.947276
Lamar Patterson  | SG       | Atlanta Hawks  | 0.525093
Terran Petteway  | SG       | Atlanta Hawks  | 0.525093
Avery Bradley    | PG       | Boston Celtics | 7.73034
Isaiah Thomas    | PG       | Boston Celtics | 6.91287
Marcus Smart     | PG       | Boston Celtics | 3.43104
... (171 rows omitted)

In [43]:
nba.where("TEAM", are.not_equal_to("Cleveland Cavaliers")).where("SALARY", are.not_below(20))

PLAYER          | POSITION | TEAM                  | SALARY
Joe Johnson     | SF       | Brooklyn Nets         | 24.8949
Derrick Rose    | PG       | Chicago Bulls         | 20.0931
Dwight Howard   | C        | Houston Rockets       | 22.3594
Chris Paul      | PG       | Los Angeles Clippers  | 21.4687
Kobe Bryant     | SF       | Los Angeles Lakers    | 25
Chris Bosh      | PF       | Miami Heat            | 22.1927
Dwyane Wade     | SG       | Miami Heat            | 20
Carmelo Anthony | SF       | New York Knicks       | 22.875
Kevin Durant    | SF       | Oklahoma City Thunder | 20.1586